# Generated by Django 3.0.6 on 2020-05-09 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editora_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgr',
            name='modified_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='bgr/modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bgr',
            name='original_image',
            field=models.ImageField(upload_to='bgr/original'),
        ),
    ]
