# Generated by Django 3.0.6 on 2020-05-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editora_api', '0002_auto_20200509_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgr',
            name='modified_image',
            field=models.ImageField(null=True, upload_to='bgr/modified'),
        ),
    ]
