# Generated by Django 3.0.6 on 2020-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editora_api', '0004_auto_20200510_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgr',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('success', 'Success'), ('failed', 'Failed'), ('processing', 'Processing')], default='queued', max_length=20),
        ),
    ]
