# Generated by Django 3.0.6 on 2020-05-16 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editora_api', '0005_bgr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgr',
            name='img_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
