# Generated by Django 3.0.6 on 2020-06-25 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editora_api', '0007_fr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='pr/original')),
                ('modified_image', models.ImageField(null=True, upload_to='pr/modified')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('img_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('success', 'Success'), ('failed', 'Failed'), ('processing', 'Processing')], default='queued', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
