# Generated by Django 3.0.6 on 2020-05-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default='havent set', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='havent set', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='havent set', max_length=100),
        ),
    ]
