# Generated by Django 3.0.6 on 2020-06-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200611_0345'),
        ('user', '0006_auto_20200625_2139'),
    ]

    operations = [
    ]
