# Generated by Django 3.0.6 on 2020-07-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_merge_20200626_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_logo',
            field=models.ImageField(null=True, upload_to='user_r/logos'),
        ),
    ]
